# Generated by Django 5.1.1 on 2024-10-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count_of_files',
            field=models.IntegerField(default=0),
        ),
    ]
